pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./gradlew'
                sh './gradlew bootJar'
            }
        }
        stage('docker build'){
            steps{
                script{
                    docker.build('owo_backend')
                }
            }
        }

        stage('docker run'){
            steps{
                sh 'docker ps -f name=owo_backend -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -f name=owo_backend -q | xargs -r docker container rm'
                sh 'docker images --no-trunc --all --quiet --filter="dangling=true" | xargs --no-run-if-empty docker rmi'
                sh 'docker run -d --name owo_backend --net {네트워크명} -p 8282:8282 owo_backend:latest'

            }
        }

    }
}