pipeline {
    agent any
    stages {

        stage('docker build'){
            steps{
                script{
                    docker.build('owo_front')
                }
            }
        }

        stage('docker run'){
            steps{
                sh 'docker ps -f name=owo_front -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -f name=owo_front -q | xargs -r docker container rm'
                sh 'docker images --no-trunc --all --quiet --filter="dangling=true" | xargs --no-run-if-empty docker rmi'
                sh 'docker run -d --name owo_front -p 8080:8080 owo_front:latest'

            }
        }
        
    }
}